-- ===========================================================================
-- 001_events_ingest.sql
-- Adds the columns the ingest pipeline needs (dedupe, source tracking, expiry,
-- images/tickets) and a moderated event_submissions table.
-- Safe to run once in the Supabase SQL editor. Idempotent where practical.
-- ===========================================================================

-- 1. New columns on events ---------------------------------------------------
alter table public.events add column if not exists source        text;
alter table public.events add column if not exists external_id   text;
alter table public.events add column if not exists dedupe_key    text;
alter table public.events add column if not exists ticket_url    text;
alter table public.events add column if not exists image_url     text;
alter table public.events add column if not exists end_date      date;
alter table public.events add column if not exists is_active     boolean not null default true;
alter table public.events add column if not exists last_seen_at  timestamptz;

-- 2. Backfill existing curated rows -----------------------------------------
update public.events set is_active = true where is_active is null;
update public.events set source = coalesce(source, 'manual');

-- Build a dedupe_key for any existing row that lacks one:
-- lower(alnum-only title) | date | lower(alnum-only city)
update public.events
set dedupe_key =
      regexp_replace(lower(coalesce(title, '')), '[^a-z0-9]', '', 'g')
      || '|' || coalesce(date::text, '')
      || '|' || regexp_replace(lower(coalesce(city, '')),  '[^a-z0-9]', '', 'g')
where dedupe_key is null;

-- 3. Unique index on dedupe_key (required for upsert onConflict) -------------
-- If this errors with a duplicate-key violation you have pre-existing dupes:
--   select dedupe_key, count(*) from public.events group by 1 having count(*) > 1;
-- ...resolve those rows, then re-run this statement.
create unique index if not exists events_dedupe_key_uidx
  on public.events (dedupe_key);

-- 4. Index to make the "active + upcoming, soonest first" UI query fast ------
create index if not exists events_active_date_idx
  on public.events (is_active, date);

-- 5. Moderated community submissions ----------------------------------------
create table if not exists public.event_submissions (
  id                bigint generated by default as identity primary key,
  title             text not null,
  date              date not null,
  location          text,
  city              text not null,
  state             text,
  description       text,
  website           text,
  categories        text[] default '{}',
  submitter_user_id uuid,
  submitter_email   text,
  dedupe_key        text unique,
  status            text not null default 'pending'
                    check (status in ('pending', 'approved', 'rejected')),
  created_at        timestamptz not null default now()
);

create index if not exists event_submissions_status_idx
  on public.event_submissions (status, created_at desc);

-- 6. Lock down submissions: all access flows through the service-key API.
--    RLS on with no anon policies = anon cannot read/write directly.
alter table public.event_submissions enable row level security;
